version: "3.5"

services:
  ce0:
    build: src/
    image: alinmear/docker-conanexiles:latest
    depends_on:
      - redis
    restart: always
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=My Cool Server 1"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
      - "CONANEXILES_UPDATE_SHUTDOWN_TIMER=15"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles

  ce1:
    image: alinmear/docker-conanexiles:latest
    depends_on:
      - redis
    restart: always
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=My Cool Server 2"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_MASTERSERVER=0"
      - "CONANEXILES_INSTANCENAME=exiles1"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7779:7777/udp
        - 27017:27015/udp
    volumes:
        - data:/conanexiles

  ce2:
    image: alinmear/docker-conanexiles:latest
    depends_on:
      - redis
    restart: always
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=My Cool Server 3"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_MASTERSERVER=0"
      - "CONANEXILES_INSTANCENAME=exiles2"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7780:7777/udp
        - 27018:27015/udp
    volumes:
        - data:/conanexiles

  redis:
    image: redis:5-alpine
    restart: always
    environment:
      - "TZ=Europe/Vienna"
    volumes:
      - redis:/data/

volumes:
    data:
    redis:
